### ISSUE TITLE
Page not being displayed

### ISSUE THREAD

**Issue by palbha** [Abdulkereem/flask-machine-learning-chatbot#1]
Hi ,
I ran the attached code , due to version issues i was unable to acced the dataset to train model indeed i trained it normwally also after running flask the page is not getting displayed the way it should .
Attaching the files , let me know what i can correct .
Thanks in advance , your code is brilliant and very nice .

![image](https://user-images.githubusercontent.com/20269788/52492999-72d1ac80-2bf0-11e9-97ca-c06657a811d6.png)

[cb.zip](https://github.com/Abdulkereem/flask-machine-learning-chatbot/files/2846021/cb.zip)

**Comment by palbha** [comment]
hi its resolved the html file being attached is improper as show on medium . Its working now .
Attaching the correct html

<html>
<head>
	<title>Friend Chatbot</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>
<div class="container">
	<div class="alert alert-primary" role="alert">
User: {{user_input}}
<div class="alert alert-dark" role="alert">
  Freind: {{bot_response}}
</div>
	
<form  action="/process" method="POST">
  <div class="form-group">
    <label for="exampleInputEmail1">Friend Chatbot
    <input type="text" name="user_input" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Talk to my friend">
  <button type="submit" class="btn btn-primary">Send
</form>
</div>
</body>
</html>

**Comment by Abdulkereem** [comment]
okay good

**Comment by Abdulkereem** [comment]
don't forget to subscribe my youtube channel and sign up on my platform

https://www.youtube.com/channel/UCwZd2y4g5uxQk7jWzghCrdA

www.codesideacademy.com

**Comment by palbha** [comment]
Thanks
